kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: proxy-service-canary
spec:
  selector:
    app: proxy-canary
  ports:
  - protocol: TCP
    port: 30000
    nodePort: 31000
    targetPort: health-check
    name: health-check
  - protocol: TCP
    port: 30001
    nodePort: 31001
    targetPort: whois
    name: whois
  - protocol: TCP
    port: 30002
    nodePort: 31002
    targetPort: epp
    name: epp
  - protocol: TCP
    port: 30010
    nodePort: 31010
    targetPort: http-whois
    name: http-whois
  - protocol: TCP
    port: 30011
    nodePort: 31011
    targetPort: https-whois
    name: https-whois
  type: NodePort
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  namespace: default
  name: proxy-autoscale-canary
  labels:
    app: proxy-canary
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: proxy-deployment-canary
  maxReplicas: 10
  minReplicas: 1
