# This is a sample production config (to be deployed in the WEB-INF directory).
# This is the same as what Google Registry runs in production, except with
# placeholders for Google-specific settings.

appEngine:
  projectId: placeholder
  # The "tools-dot-" prefix is used on the project ID in this URL in order to
  # get around an issue with double-wildcard SSL certs.
  toolsServiceUrl:
    hostName: tools-dot-placeholder.appspot.com
    port: 443

gSuite:
  domainName: placeholder
  outgoingEmailDisplayName: placeholder
  outgoingEmailAddress: placeholder
  adminAccountEmailAddress: placeholder

registryPolicy:
  contactAndHostRoidSuffix: placeholder
  productName: placeholder
  greetingServerId: placeholder
  registrarChangesNotificationEmailAddresses:
    - placeholder
    - placeholder
  defaultRegistrarWhoisServer: placeholder
  defaultRegistrarReferralUrl: placeholder
  tmchCaMode: PRODUCTION
  tmchCrlUrl: http://crl.icann.org/tmch.crl
  tmchMarksDbUrl: https://ry.marksdb.org
  checkApiServletClientId: |
    multi-line
    placeholder
  whoisDisclaimer: |
    multi-line
    placeholder

rde:
  reportUrlPrefix: https://ry-api.icann.org/report/registry-escrow-report
  uploadUrl: sftp://placeholder@sftpipm2.ironmountain.com/Outbox
  sshIdentityEmailAddress: placeholder

registrarConsole:
  logoFilename: placeholder
  supportPhoneNumber: placeholder
  supportEmailAddress: placeholder
  announcementsEmailAddress: placeholder
  integrationEmailAddress: placeholder
  technicalDocsUrl: https://drive.google.com/drive/folders/placeholder

misc:
  sheetExportId: placeholder

rdap:
  baseUrl: placeholder

# You only need to specify this section if using Braintree.
braintree:
  merchantId: placeholder
  publicKey: placeholder
  # Only include currencies that you use.
  merchantAccountIdsMap:
    EUR: placeholder
    JPY: placeholder
    USD: placeholder
